//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanManagementService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MealPlan", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class MealPlan : object
    {
        
        private string CommentsField;
        
        private int IdMealPlanField;
        
        private int IdPatientField;
        
        private PlanManagementService.Meal[] MealsField;
        
        private System.DateTime PlanDateField;
        
        private string PlanDescriptionField;
        
        private string RecommendationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMealPlan
        {
            get
            {
                return this.IdMealPlanField;
            }
            set
            {
                this.IdMealPlanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPatient
        {
            get
            {
                return this.IdPatientField;
            }
            set
            {
                this.IdPatientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlanManagementService.Meal[] Meals
        {
            get
            {
                return this.MealsField;
            }
            set
            {
                this.MealsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PlanDate
        {
            get
            {
                return this.PlanDateField;
            }
            set
            {
                this.PlanDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanDescription
        {
            get
            {
                return this.PlanDescriptionField;
            }
            set
            {
                this.PlanDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recommendations
        {
            get
            {
                return this.RecommendationsField;
            }
            set
            {
                this.RecommendationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Meal", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class Meal : object
    {
        
        private string EquivalencesField;
        
        private int IdMealField;
        
        private int IdMealPlanField;
        
        private string MealExamplesField;
        
        private string MealTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equivalences
        {
            get
            {
                return this.EquivalencesField;
            }
            set
            {
                this.EquivalencesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMeal
        {
            get
            {
                return this.IdMealField;
            }
            set
            {
                this.IdMealField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMealPlan
        {
            get
            {
                return this.IdMealPlanField;
            }
            set
            {
                this.IdMealPlanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MealExamples
        {
            get
            {
                return this.MealExamplesField;
            }
            set
            {
                this.MealExamplesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MealType
        {
            get
            {
                return this.MealTypeField;
            }
            set
            {
                this.MealTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlanManagementService.IPlanManagementService")]
    public interface IPlanManagementService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanManagementService/AddNewMealPlan", ReplyAction="http://tempuri.org/IPlanManagementService/AddNewMealPlanResponse")]
        System.Threading.Tasks.Task<int> AddNewMealPlanAsync(PlanManagementService.MealPlan plan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanManagementService/UpdateMeal", ReplyAction="http://tempuri.org/IPlanManagementService/UpdateMealResponse")]
        System.Threading.Tasks.Task<int> UpdateMealAsync(PlanManagementService.Meal meal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanManagementService/UpdateMealPlan", ReplyAction="http://tempuri.org/IPlanManagementService/UpdateMealPlanResponse")]
        System.Threading.Tasks.Task<int> UpdateMealPlanAsync(PlanManagementService.MealPlan mealplan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanManagementService/GetLastMealPlan", ReplyAction="http://tempuri.org/IPlanManagementService/GetLastMealPlanResponse")]
        System.Threading.Tasks.Task<PlanManagementService.MealPlan> GetLastMealPlanAsync(int patientId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IPlanManagementServiceChannel : PlanManagementService.IPlanManagementService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class PlanManagementServiceClient : System.ServiceModel.ClientBase<PlanManagementService.IPlanManagementService>, PlanManagementService.IPlanManagementService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PlanManagementServiceClient() : 
                base(PlanManagementServiceClient.GetDefaultBinding(), PlanManagementServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPlanManagementService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlanManagementServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PlanManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), PlanManagementServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlanManagementServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PlanManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlanManagementServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PlanManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PlanManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> AddNewMealPlanAsync(PlanManagementService.MealPlan plan)
        {
            return base.Channel.AddNewMealPlanAsync(plan);
        }
        
        public System.Threading.Tasks.Task<int> UpdateMealAsync(PlanManagementService.Meal meal)
        {
            return base.Channel.UpdateMealAsync(meal);
        }
        
        public System.Threading.Tasks.Task<int> UpdateMealPlanAsync(PlanManagementService.MealPlan mealplan)
        {
            return base.Channel.UpdateMealPlanAsync(mealplan);
        }
        
        public System.Threading.Tasks.Task<PlanManagementService.MealPlan> GetLastMealPlanAsync(int patientId)
        {
            return base.Channel.GetLastMealPlanAsync(patientId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPlanManagementService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPlanManagementService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50933/Services/PlanManagementService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PlanManagementServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPlanManagementService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PlanManagementServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPlanManagementService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPlanManagementService,
        }
    }
}
