//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgressManagementService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Diagnosis", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class Diagnosis : object
    {
        
        private string AppetiteField;
        
        private ProgressManagementService.BodyCompositions BodyCompositionField;
        
        private System.DateTime DiagnosisDateField;
        
        private string DreamField;
        
        private string EnergyLevelField;
        
        private string FeedingField;
        
        private string GeneralCommentsField;
        
        private int IdDiagnosisField;
        
        private ProgressManagementService.DiagnosisImage ImageField;
        
        private ProgressManagementService.Measure MeasureField;
        
        private int PatientIdField;
        
        private string PhysicalActivityField;
        
        private string PhysicalPerceptionField;
        
        private string StomachUpsetField;
        
        private string StressLevelField;
        
        private string SubstanceUseField;
        
        private string WaterConsumptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Appetite
        {
            get
            {
                return this.AppetiteField;
            }
            set
            {
                this.AppetiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProgressManagementService.BodyCompositions BodyComposition
        {
            get
            {
                return this.BodyCompositionField;
            }
            set
            {
                this.BodyCompositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DiagnosisDate
        {
            get
            {
                return this.DiagnosisDateField;
            }
            set
            {
                this.DiagnosisDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dream
        {
            get
            {
                return this.DreamField;
            }
            set
            {
                this.DreamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnergyLevel
        {
            get
            {
                return this.EnergyLevelField;
            }
            set
            {
                this.EnergyLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Feeding
        {
            get
            {
                return this.FeedingField;
            }
            set
            {
                this.FeedingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralComments
        {
            get
            {
                return this.GeneralCommentsField;
            }
            set
            {
                this.GeneralCommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDiagnosis
        {
            get
            {
                return this.IdDiagnosisField;
            }
            set
            {
                this.IdDiagnosisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProgressManagementService.DiagnosisImage Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProgressManagementService.Measure Measure
        {
            get
            {
                return this.MeasureField;
            }
            set
            {
                this.MeasureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PatientId
        {
            get
            {
                return this.PatientIdField;
            }
            set
            {
                this.PatientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhysicalActivity
        {
            get
            {
                return this.PhysicalActivityField;
            }
            set
            {
                this.PhysicalActivityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhysicalPerception
        {
            get
            {
                return this.PhysicalPerceptionField;
            }
            set
            {
                this.PhysicalPerceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StomachUpset
        {
            get
            {
                return this.StomachUpsetField;
            }
            set
            {
                this.StomachUpsetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StressLevel
        {
            get
            {
                return this.StressLevelField;
            }
            set
            {
                this.StressLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubstanceUse
        {
            get
            {
                return this.SubstanceUseField;
            }
            set
            {
                this.SubstanceUseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WaterConsumption
        {
            get
            {
                return this.WaterConsumptionField;
            }
            set
            {
                this.WaterConsumptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BodyCompositions", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class BodyCompositions : object
    {
        
        private double FatPercentageField;
        
        private int IdBodyCompositionField;
        
        private int IdDiagnosisField;
        
        private int IdPatientField;
        
        private double MusclePercentageField;
        
        private double TotalWeightField;
        
        private double VisceralFatField;
        
        private double WaterPercentageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FatPercentage
        {
            get
            {
                return this.FatPercentageField;
            }
            set
            {
                this.FatPercentageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBodyComposition
        {
            get
            {
                return this.IdBodyCompositionField;
            }
            set
            {
                this.IdBodyCompositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDiagnosis
        {
            get
            {
                return this.IdDiagnosisField;
            }
            set
            {
                this.IdDiagnosisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPatient
        {
            get
            {
                return this.IdPatientField;
            }
            set
            {
                this.IdPatientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MusclePercentage
        {
            get
            {
                return this.MusclePercentageField;
            }
            set
            {
                this.MusclePercentageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalWeight
        {
            get
            {
                return this.TotalWeightField;
            }
            set
            {
                this.TotalWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double VisceralFat
        {
            get
            {
                return this.VisceralFatField;
            }
            set
            {
                this.VisceralFatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double WaterPercentage
        {
            get
            {
                return this.WaterPercentageField;
            }
            set
            {
                this.WaterPercentageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiagnosisImage", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class DiagnosisImage : object
    {
        
        private string CommentsField;
        
        private int IdDiagnosisField;
        
        private int IdImageField;
        
        private byte[] ImageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDiagnosis
        {
            get
            {
                return this.IdDiagnosisField;
            }
            set
            {
                this.IdDiagnosisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdImage
        {
            get
            {
                return this.IdImageField;
            }
            set
            {
                this.IdImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Measure", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class Measure : object
    {
        
        private double ArmField;
        
        private double CalfField;
        
        private double ChestField;
        
        private double ContractedArmField;
        
        private double ForearmField;
        
        private double HipField;
        
        private int IdDiagnosisField;
        
        private int IdMeasureField;
        
        private int IdPatientField;
        
        private double ThighField;
        
        private double WaistField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Arm
        {
            get
            {
                return this.ArmField;
            }
            set
            {
                this.ArmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Calf
        {
            get
            {
                return this.CalfField;
            }
            set
            {
                this.CalfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Chest
        {
            get
            {
                return this.ChestField;
            }
            set
            {
                this.ChestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ContractedArm
        {
            get
            {
                return this.ContractedArmField;
            }
            set
            {
                this.ContractedArmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Forearm
        {
            get
            {
                return this.ForearmField;
            }
            set
            {
                this.ForearmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Hip
        {
            get
            {
                return this.HipField;
            }
            set
            {
                this.HipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDiagnosis
        {
            get
            {
                return this.IdDiagnosisField;
            }
            set
            {
                this.IdDiagnosisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMeasure
        {
            get
            {
                return this.IdMeasureField;
            }
            set
            {
                this.IdMeasureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPatient
        {
            get
            {
                return this.IdPatientField;
            }
            set
            {
                this.IdPatientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Thigh
        {
            get
            {
                return this.ThighField;
            }
            set
            {
                this.ThighField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Waist
        {
            get
            {
                return this.WaistField;
            }
            set
            {
                this.WaistField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProgressManagementService.IProgressManagementService")]
    public interface IProgressManagementService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgressManagementService/AddNewDiagnosis", ReplyAction="http://tempuri.org/IProgressManagementService/AddNewDiagnosisResponse")]
        System.Threading.Tasks.Task<int> AddNewDiagnosisAsync(ProgressManagementService.Diagnosis diagnosis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgressManagementService/GetLastDiagnosis", ReplyAction="http://tempuri.org/IProgressManagementService/GetLastDiagnosisResponse")]
        System.Threading.Tasks.Task<ProgressManagementService.Diagnosis> GetLastDiagnosisAsync(int patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgressManagementService/GetDiagnosisByPatient", ReplyAction="http://tempuri.org/IProgressManagementService/GetDiagnosisByPatientResponse")]
        System.Threading.Tasks.Task<ProgressManagementService.Diagnosis[]> GetDiagnosisByPatientAsync(int patientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgressManagementService/UpdateDiagnosis", ReplyAction="http://tempuri.org/IProgressManagementService/UpdateDiagnosisResponse")]
        System.Threading.Tasks.Task<int> UpdateDiagnosisAsync(ProgressManagementService.Diagnosis diagnosis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgressManagementService/UpdateMeasures", ReplyAction="http://tempuri.org/IProgressManagementService/UpdateMeasuresResponse")]
        System.Threading.Tasks.Task<int> UpdateMeasuresAsync(ProgressManagementService.Measure measure);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgressManagementService/UpdateBodyComposition", ReplyAction="http://tempuri.org/IProgressManagementService/UpdateBodyCompositionResponse")]
        System.Threading.Tasks.Task<int> UpdateBodyCompositionAsync(ProgressManagementService.BodyCompositions bodyCompositions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgressManagementService/GetMeasuresByPatient", ReplyAction="http://tempuri.org/IProgressManagementService/GetMeasuresByPatientResponse")]
        System.Threading.Tasks.Task<ProgressManagementService.Measure[]> GetMeasuresByPatientAsync(int patientId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IProgressManagementServiceChannel : ProgressManagementService.IProgressManagementService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ProgressManagementServiceClient : System.ServiceModel.ClientBase<ProgressManagementService.IProgressManagementService>, ProgressManagementService.IProgressManagementService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProgressManagementServiceClient() : 
                base(ProgressManagementServiceClient.GetDefaultBinding(), ProgressManagementServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IProgressManagementService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgressManagementServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ProgressManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), ProgressManagementServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgressManagementServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProgressManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgressManagementServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProgressManagementServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgressManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> AddNewDiagnosisAsync(ProgressManagementService.Diagnosis diagnosis)
        {
            return base.Channel.AddNewDiagnosisAsync(diagnosis);
        }
        
        public System.Threading.Tasks.Task<ProgressManagementService.Diagnosis> GetLastDiagnosisAsync(int patientId)
        {
            return base.Channel.GetLastDiagnosisAsync(patientId);
        }
        
        public System.Threading.Tasks.Task<ProgressManagementService.Diagnosis[]> GetDiagnosisByPatientAsync(int patientId)
        {
            return base.Channel.GetDiagnosisByPatientAsync(patientId);
        }
        
        public System.Threading.Tasks.Task<int> UpdateDiagnosisAsync(ProgressManagementService.Diagnosis diagnosis)
        {
            return base.Channel.UpdateDiagnosisAsync(diagnosis);
        }
        
        public System.Threading.Tasks.Task<int> UpdateMeasuresAsync(ProgressManagementService.Measure measure)
        {
            return base.Channel.UpdateMeasuresAsync(measure);
        }
        
        public System.Threading.Tasks.Task<int> UpdateBodyCompositionAsync(ProgressManagementService.BodyCompositions bodyCompositions)
        {
            return base.Channel.UpdateBodyCompositionAsync(bodyCompositions);
        }
        
        public System.Threading.Tasks.Task<ProgressManagementService.Measure[]> GetMeasuresByPatientAsync(int patientId)
        {
            return base.Channel.GetMeasuresByPatientAsync(patientId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProgressManagementService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProgressManagementService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50933/Services/ProgressManagementService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProgressManagementServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IProgressManagementService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProgressManagementServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IProgressManagementService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IProgressManagementService,
        }
    }
}
