//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagementService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class Patient : object
    {
        
        private System.DateTime BirthdayField;
        
        private string GenderField;
        
        private UserManagementService.GeneralInformation GeneralInfomationField;
        
        private UserManagementService.HabitsAndGoals HabitsAndGoalsField;
        
        private float HeightField;
        
        private int IdPatientField;
        
        private UserManagementService.MedicalInformation MedicalInformationField;
        
        private int NutritionistField;
        
        private UserManagementService.Person PersonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthday
        {
            get
            {
                return this.BirthdayField;
            }
            set
            {
                this.BirthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementService.GeneralInformation GeneralInfomation
        {
            get
            {
                return this.GeneralInfomationField;
            }
            set
            {
                this.GeneralInfomationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementService.HabitsAndGoals HabitsAndGoals
        {
            get
            {
                return this.HabitsAndGoalsField;
            }
            set
            {
                this.HabitsAndGoalsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPatient
        {
            get
            {
                return this.IdPatientField;
            }
            set
            {
                this.IdPatientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementService.MedicalInformation MedicalInformation
        {
            get
            {
                return this.MedicalInformationField;
            }
            set
            {
                this.MedicalInformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nutritionist
        {
            get
            {
                return this.NutritionistField;
            }
            set
            {
                this.NutritionistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementService.Person Person
        {
            get
            {
                return this.PersonField;
            }
            set
            {
                this.PersonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralInformation", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class GeneralInformation : object
    {
        
        private string DietarySupplementsField;
        
        private string EatingEmotionalBehaviorField;
        
        private string FavoriteFoodsField;
        
        private string GeneralCommentsField;
        
        private int IdGeneralInformationField;
        
        private string NonFavoriteFoodsField;
        
        private string NutritionalFamiliarityField;
        
        private int PhysicalActivityField;
        
        private string PhysicalActivityCommentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DietarySupplements
        {
            get
            {
                return this.DietarySupplementsField;
            }
            set
            {
                this.DietarySupplementsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EatingEmotionalBehavior
        {
            get
            {
                return this.EatingEmotionalBehaviorField;
            }
            set
            {
                this.EatingEmotionalBehaviorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavoriteFoods
        {
            get
            {
                return this.FavoriteFoodsField;
            }
            set
            {
                this.FavoriteFoodsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralComments
        {
            get
            {
                return this.GeneralCommentsField;
            }
            set
            {
                this.GeneralCommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGeneralInformation
        {
            get
            {
                return this.IdGeneralInformationField;
            }
            set
            {
                this.IdGeneralInformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NonFavoriteFoods
        {
            get
            {
                return this.NonFavoriteFoodsField;
            }
            set
            {
                this.NonFavoriteFoodsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NutritionalFamiliarity
        {
            get
            {
                return this.NutritionalFamiliarityField;
            }
            set
            {
                this.NutritionalFamiliarityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhysicalActivity
        {
            get
            {
                return this.PhysicalActivityField;
            }
            set
            {
                this.PhysicalActivityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhysicalActivityComments
        {
            get
            {
                return this.PhysicalActivityCommentsField;
            }
            set
            {
                this.PhysicalActivityCommentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HabitsAndGoals", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class HabitsAndGoals : object
    {
        
        private string AlcoholField;
        
        private string CaffeineField;
        
        private string CigaretteField;
        
        private string DrugsField;
        
        private string ExpectationsField;
        
        private string GeneralCommentField;
        
        private string HealthGoalsField;
        
        private int IdHabitsAndGoalsField;
        
        private string SpecificNutritionalGoalsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alcohol
        {
            get
            {
                return this.AlcoholField;
            }
            set
            {
                this.AlcoholField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caffeine
        {
            get
            {
                return this.CaffeineField;
            }
            set
            {
                this.CaffeineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cigarette
        {
            get
            {
                return this.CigaretteField;
            }
            set
            {
                this.CigaretteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Drugs
        {
            get
            {
                return this.DrugsField;
            }
            set
            {
                this.DrugsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expectations
        {
            get
            {
                return this.ExpectationsField;
            }
            set
            {
                this.ExpectationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralComment
        {
            get
            {
                return this.GeneralCommentField;
            }
            set
            {
                this.GeneralCommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HealthGoals
        {
            get
            {
                return this.HealthGoalsField;
            }
            set
            {
                this.HealthGoalsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdHabitsAndGoals
        {
            get
            {
                return this.IdHabitsAndGoalsField;
            }
            set
            {
                this.IdHabitsAndGoalsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecificNutritionalGoals
        {
            get
            {
                return this.SpecificNutritionalGoalsField;
            }
            set
            {
                this.SpecificNutritionalGoalsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicalInformation", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class MedicalInformation : object
    {
        
        private string ChronicDiseasesField;
        
        private string FoodAllergiesField;
        
        private string GastrointestinalDiseasesField;
        
        private string GeneralMedicalCommentsField;
        
        private string HereditaryFamilyHistoryField;
        
        private int IdMedicalInformationField;
        
        private string MedicationsField;
        
        private string NonFoodAllergiesField;
        
        private string SurgicalHistoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChronicDiseases
        {
            get
            {
                return this.ChronicDiseasesField;
            }
            set
            {
                this.ChronicDiseasesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodAllergies
        {
            get
            {
                return this.FoodAllergiesField;
            }
            set
            {
                this.FoodAllergiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GastrointestinalDiseases
        {
            get
            {
                return this.GastrointestinalDiseasesField;
            }
            set
            {
                this.GastrointestinalDiseasesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralMedicalComments
        {
            get
            {
                return this.GeneralMedicalCommentsField;
            }
            set
            {
                this.GeneralMedicalCommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HereditaryFamilyHistory
        {
            get
            {
                return this.HereditaryFamilyHistoryField;
            }
            set
            {
                this.HereditaryFamilyHistoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMedicalInformation
        {
            get
            {
                return this.IdMedicalInformationField;
            }
            set
            {
                this.IdMedicalInformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Medications
        {
            get
            {
                return this.MedicationsField;
            }
            set
            {
                this.MedicationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NonFoodAllergies
        {
            get
            {
                return this.NonFoodAllergiesField;
            }
            set
            {
                this.NonFoodAllergiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurgicalHistory
        {
            get
            {
                return this.SurgicalHistoryField;
            }
            set
            {
                this.SurgicalHistoryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class Person : object
    {
        
        private string EmailField;
        
        private string FirstLastNameField;
        
        private int IdPersonField;
        
        private string NamesField;
        
        private string PhoneField;
        
        private string SecondLastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstLastName
        {
            get
            {
                return this.FirstLastNameField;
            }
            set
            {
                this.FirstLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPerson
        {
            get
            {
                return this.IdPersonField;
            }
            set
            {
                this.IdPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Names
        {
            get
            {
                return this.NamesField;
            }
            set
            {
                this.NamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondLastName
        {
            get
            {
                return this.SecondLastNameField;
            }
            set
            {
                this.SecondLastNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nutritionist", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class Nutritionist : object
    {
        
        private int IdNutritionistField;
        
        private UserManagementService.Person PersonField;
        
        private string ProfessionalIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNutritionist
        {
            get
            {
                return this.IdNutritionistField;
            }
            set
            {
                this.IdNutritionistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementService.Person Person
        {
            get
            {
                return this.PersonField;
            }
            set
            {
                this.PersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfessionalId
        {
            get
            {
                return this.ProfessionalIdField;
            }
            set
            {
                this.ProfessionalIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManagementService.UserManagement")]
    public interface UserManagement
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserManagement/AddPatient", ReplyAction="http://tempuri.org/UserManagement/AddPatientResponse")]
        System.Threading.Tasks.Task<int> AddPatientAsync(UserManagementService.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserManagement/UpdatePatient", ReplyAction="http://tempuri.org/UserManagement/UpdatePatientResponse")]
        System.Threading.Tasks.Task<int> UpdatePatientAsync(UserManagementService.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserManagement/UpdateMedicalInformation", ReplyAction="http://tempuri.org/UserManagement/UpdateMedicalInformationResponse")]
        System.Threading.Tasks.Task<int> UpdateMedicalInformationAsync(UserManagementService.MedicalInformation information);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserManagement/GetPatient", ReplyAction="http://tempuri.org/UserManagement/GetPatientResponse")]
        System.Threading.Tasks.Task<UserManagementService.Patient> GetPatientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserManagement/GetMyPatients", ReplyAction="http://tempuri.org/UserManagement/GetMyPatientsResponse")]
        System.Threading.Tasks.Task<UserManagementService.Patient[]> GetMyPatientsAsync(int NutritionistId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserManagement/FilterPatients", ReplyAction="http://tempuri.org/UserManagement/FilterPatientsResponse")]
        System.Threading.Tasks.Task<UserManagementService.Patient[]> FilterPatientsAsync(int nutritionistId, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserManagement/LogIn", ReplyAction="http://tempuri.org/UserManagement/LogInResponse")]
        System.Threading.Tasks.Task<UserManagementService.Nutritionist> LogInAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface UserManagementChannel : UserManagementService.UserManagement, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class UserManagementClient : System.ServiceModel.ClientBase<UserManagementService.UserManagement>, UserManagementService.UserManagement
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserManagementClient() : 
                base(UserManagementClient.GetDefaultBinding(), UserManagementClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_UserManagement.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementClient(EndpointConfiguration endpointConfiguration) : 
                base(UserManagementClient.GetBindingForEndpoint(endpointConfiguration), UserManagementClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserManagementClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserManagementClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> AddPatientAsync(UserManagementService.Patient patient)
        {
            return base.Channel.AddPatientAsync(patient);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePatientAsync(UserManagementService.Patient patient)
        {
            return base.Channel.UpdatePatientAsync(patient);
        }
        
        public System.Threading.Tasks.Task<int> UpdateMedicalInformationAsync(UserManagementService.MedicalInformation information)
        {
            return base.Channel.UpdateMedicalInformationAsync(information);
        }
        
        public System.Threading.Tasks.Task<UserManagementService.Patient> GetPatientAsync(int id)
        {
            return base.Channel.GetPatientAsync(id);
        }
        
        public System.Threading.Tasks.Task<UserManagementService.Patient[]> GetMyPatientsAsync(int NutritionistId)
        {
            return base.Channel.GetMyPatientsAsync(NutritionistId);
        }
        
        public System.Threading.Tasks.Task<UserManagementService.Patient[]> FilterPatientsAsync(int nutritionistId, string filter)
        {
            return base.Channel.FilterPatientsAsync(nutritionistId, filter);
        }
        
        public System.Threading.Tasks.Task<UserManagementService.Nutritionist> LogInAsync(string username, string password)
        {
            return base.Channel.LogInAsync(username, password);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_UserManagement))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_UserManagement))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50933/Services/UserManagementService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UserManagementClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_UserManagement);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UserManagementClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_UserManagement);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_UserManagement,
        }
    }
}
