//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagementService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class Patient : object
    {
        
        private System.DateTime BirthdayField;
        
        private UserManagementService.GeneralInformation GeneralInfomationField;
        
        private double HeightField;
        
        private int IdPatientField;
        
        private UserManagementService.MedicalInformation MedicalInformationField;
        
        private int NutritionistField;
        
        private UserManagementService.Person PersonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthday
        {
            get
            {
                return this.BirthdayField;
            }
            set
            {
                this.BirthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementService.GeneralInformation GeneralInfomation
        {
            get
            {
                return this.GeneralInfomationField;
            }
            set
            {
                this.GeneralInfomationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPatient
        {
            get
            {
                return this.IdPatientField;
            }
            set
            {
                this.IdPatientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementService.MedicalInformation MedicalInformation
        {
            get
            {
                return this.MedicalInformationField;
            }
            set
            {
                this.MedicalInformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nutritionist
        {
            get
            {
                return this.NutritionistField;
            }
            set
            {
                this.NutritionistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementService.Person Person
        {
            get
            {
                return this.PersonField;
            }
            set
            {
                this.PersonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralInformation", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class GeneralInformation : object
    {
        
        private string FoodPreferencesField;
        
        private string GeneralCommentsField;
        
        private int IdGeneralInformationField;
        
        private int PhysicalActivityField;
        
        private string PhysicalActivityCommentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodPreferences
        {
            get
            {
                return this.FoodPreferencesField;
            }
            set
            {
                this.FoodPreferencesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralComments
        {
            get
            {
                return this.GeneralCommentsField;
            }
            set
            {
                this.GeneralCommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGeneralInformation
        {
            get
            {
                return this.IdGeneralInformationField;
            }
            set
            {
                this.IdGeneralInformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhysicalActivity
        {
            get
            {
                return this.PhysicalActivityField;
            }
            set
            {
                this.PhysicalActivityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhysicalActivityComments
        {
            get
            {
                return this.PhysicalActivityCommentsField;
            }
            set
            {
                this.PhysicalActivityCommentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicalInformation", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class MedicalInformation : object
    {
        
        private string AllergiesField;
        
        private string DiseasesField;
        
        private int IdMedicalInformationField;
        
        private string MedicinesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Allergies
        {
            get
            {
                return this.AllergiesField;
            }
            set
            {
                this.AllergiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diseases
        {
            get
            {
                return this.DiseasesField;
            }
            set
            {
                this.DiseasesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMedicalInformation
        {
            get
            {
                return this.IdMedicalInformationField;
            }
            set
            {
                this.IdMedicalInformationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Medicines
        {
            get
            {
                return this.MedicinesField;
            }
            set
            {
                this.MedicinesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/HealthDiveneSysServer.Entities")]
    public partial class Person : object
    {
        
        private string EmailField;
        
        private string FirstLastNameField;
        
        private int IdPersonField;
        
        private string NamesField;
        
        private string PhoneField;
        
        private string SecondLastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstLastName
        {
            get
            {
                return this.FirstLastNameField;
            }
            set
            {
                this.FirstLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPerson
        {
            get
            {
                return this.IdPersonField;
            }
            set
            {
                this.IdPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Names
        {
            get
            {
                return this.NamesField;
            }
            set
            {
                this.NamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondLastName
        {
            get
            {
                return this.SecondLastNameField;
            }
            set
            {
                this.SecondLastNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManagementService.UserManagement")]
    public interface UserManagement
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserManagement/AddPatient", ReplyAction="http://tempuri.org/UserManagement/AddPatientResponse")]
        System.Threading.Tasks.Task<int> AddPatientAsync(UserManagementService.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserManagement/GetMyPatients", ReplyAction="http://tempuri.org/UserManagement/GetMyPatientsResponse")]
        System.Threading.Tasks.Task<UserManagementService.Patient[]> GetMyPatientsAsync(int NutritionistId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface UserManagementChannel : UserManagementService.UserManagement, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class UserManagementClient : System.ServiceModel.ClientBase<UserManagementService.UserManagement>, UserManagementService.UserManagement
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserManagementClient() : 
                base(UserManagementClient.GetDefaultBinding(), UserManagementClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_UserManagement.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementClient(EndpointConfiguration endpointConfiguration) : 
                base(UserManagementClient.GetBindingForEndpoint(endpointConfiguration), UserManagementClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserManagementClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserManagementClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> AddPatientAsync(UserManagementService.Patient patient)
        {
            return base.Channel.AddPatientAsync(patient);
        }
        
        public System.Threading.Tasks.Task<UserManagementService.Patient[]> GetMyPatientsAsync(int NutritionistId)
        {
            return base.Channel.GetMyPatientsAsync(NutritionistId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_UserManagement))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_UserManagement))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50933/Services/UserManagementService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UserManagementClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_UserManagement);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UserManagementClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_UserManagement);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_UserManagement,
        }
    }
}
